version: '2'

volumes:
  volume_mysql:
    driver: local
  volume_redis:
    driver: local

networks:
  local-network:
    driver: bridge

services:
  mysql_server:
    image: mysql:5.7
    volumes:
        - volume_mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: passwd
        MYSQL_DATABASE: test
    ports:
      - "6033:3306"
    networks:
      - local-network

  redis_server:
    image: redis:alpine
    volumes:
      - volume_redis:/data
    ports:
      - "9736:6379"
    networks:
      - local-network
